// 🌍 ==========================================
// MOTOR DE IDIOMAS (INTERNACIONALIZACIÓN)
// ==========================================
const langToggle = document.getElementById('langToggle');
const langToggleMobile = document.getElementById('langToggleMobile');
const currentLangLabel = document.getElementById('currentLang');
const currentLangLabelMobile = document.getElementById('currentLangMobile');

// Diccionario de Traducciones
const translations = {
    es: {
        nav_features: "Características",
        nav_how: "Cómo Funciona",
        nav_privacy: "Privacidad",
        nav_impact: "Impacto:",
        nav_impact_total: "Impacto total:",
        hero_title_1: "Compresión inteligente.",
        hero_title_2: "Calidad intacta.",
        hero_subtitle: "Optimización premium que ocurre directamente en tu dispositivo. Más velocidad, máxima privacidad y sin límites.",
        drop_main: "Arrastra tus imágenes aquí",
        drop_sub: "o haz clic para explorar tus archivos",
        drop_limit: '<i data-lucide="shield-check" class="w-4 h-4"></i> Límite 10MB (JPG, PNG, WEBP)',
        settings_title: "Ajustes Básicos",
        settings_quality: "Calidad",
        settings_format: "Formato de salida",
        format_original: "ORIGINAL",
        pro_title: "Herramientas PRO",
        pro_badge: "Funciones Premium",
        resize_label: "Redimensionar",
        resize_0: "Mantener Original",
        resize_4k: "4K (Max 3840px)",
        resize_fhd: "Full HD (Max 1920px)",
        resize_web: "Web / RRSS (Max 1080px)",
        resize_mini: "Mini / Rápido (Max 720px)",
        resize_mobile: "Móvil / Correo (Max 480px)",
        resize_icon: "Icono / Perfil (Max 360px)",
        watermark_label: "Marca de Agua",
        watermark_placeholder: "@TuMarca o Texto...",
        anti_track_label: "Anti-Rastreo",
        anti_track_sub: "Limpia GPS / EXIF",
        btn_compress: "Comprimir Imágenes",
        preview_original: "Original",
        preview_result: "Resultado",
        waiting_image: "Esperando imagen",
        waiting_magic: "Esperando magia...",
        stats_title: "Ahorro de Peso",
        stats_waiting: "Esperando imagen...",
        btn_download: "Descargar Imagen",
        tech_title_1: "Tecnología de",
        tech_title_2: "Vanguardia",
        tech_subtitle: "Por qué Compressly es la herramienta definitiva para profesionales.",
        tech_local_title: "Compresión Local",
        tech_local_desc: "Usamos el procesador de tu dispositivo. Sin colas de espera, sin servidores caídos, velocidad instantánea.",
        tech_formats_title: "Múltiples Formatos",
        tech_formats_desc: "Soporte total para JPG, PNG, y conversión automática a WebP para sitios web de última generación.",
        tech_privacy_title: "Privacidad Militar",
        tech_privacy_desc: "Tus imágenes nunca viajan por internet. Se procesan y se quedan en tu memoria RAM. 100% libre de hackeos.",
        tech_privacy_link: 'Leer política legal <i data-lucide="arrow-right" class="w-3 h-3"></i>',
        magic_title_1: "¿Cómo ocurre la",
        magic_title_2: "Magia?",
        magic_subtitle: "Un flujo de optimización que nunca abandona tu pantalla.",
        magic_step1_title: "1. Selección",
        magic_step1_desc: "Arrastras tu imagen de hasta 10MB. El archivo es leído únicamente por el navegador de tu dispositivo.",
        magic_step2_title: "2. Motor Local",
        magic_step2_desc: "El procesador de tu equipo comprime los píxeles utilizando tecnología avanzada sin usar internet.",
        magic_step3_title: "3. Exportación",
        magic_step3_desc: "Obtienes la imagen optimizada al instante. Cero tiempos de carga o de bajada desde servidores.",
        batch_title: "Lote de Imágenes",
        batch_folders: "Carpetas",
        batch_prefix: "Prefijo (Opcional)",
        batch_saving: "Ahorro del Lote",
        batch_waiting: "Esperando orden...",
        batch_queue: "En cola",
        batch_btn_download: "Descargar ZIP",
        test_title_1: "Amado por",
        test_title_2: "Profesionales",
        test_sub: "Miles de gigabytes ahorrados alrededor del mundo.",
        test1_text: '"Gestión de tiendas e-commerce es mi día a día. Antes perdía horas subiendo fotos a otros compresores. Con Compressly, proceso lotes enteros en segundos y sin salir de mi pantalla."',
        test1_role: "Diseñadora Web",
        test2_text: '"Como fotógrafa, mi peor pesadilla es que roben mi material original. Saber que la compresión es 100% local en mi RAM me da una tranquilidad impagable."',
        test2_role: "Fotógrafa Profesional",
        test3_text: '"La herramienta de renombrado en lote y organización por carpetas ZIP me ahorró pagarle a un asistente. Es una locura que esto funcione directo en el navegador."',
        test3_role: "Agencia de Marketing",
        price_title_1: "Planes Simples,",
        price_title_2: "Poder Absoluto",
        price_sub: "Elige el plan que se adapte a tu flujo de trabajo.",
        plan_free_title: "Esencial",
        plan_free_sub: "Perfecto para uso ocasional y personal.",
        plan_free_price: "$0",
        plan_free_time: "/ de por vida",
        plan_free_f1: "Compresión Local (Sin internet)",
        plan_free_f2: "Hasta 3 imágenes a la vez",
        plan_free_f3: "Máximo 10MB por archivo",
        plan_free_f4: "Redimensionar y Marca de Agua",
        plan_free_f5: "Carpetas ZIP y Escudo GPS",
        plan_free_btn: "Comenzar Gratis",
        plan_pro_badge: "Más Popular",
        plan_pro_sub: "Para agencias, fotógrafos y e-commerce.",
        plan_pro_price: "$19.99",
        plan_pro_time: "/ de por vida",
        plan_pro_f1: "Lotes ILIMITADOS de imágenes",
        plan_pro_f2: "Archivos gigantes (+10MB)",
        plan_pro_f3: "Marca de Agua y Redimensionado Inteligente",
        plan_pro_f4: "Escudo Anti-Rastreo (GPS)",
        plan_pro_f5: "Organización automática en ZIP",
        plan_pro_btn: "Obtener Acceso PRO",
        faq_title: "Preguntas Frecuentes",
        faq1_q: "¿De verdad mis fotos no se suben a internet?",
        faq1_a: "Absolutamente. Compressly utiliza una tecnología llamada WebAssembly. Todo el motor de compresión se descarga en tu navegador la primera vez que entras. Cuando arrastras una foto, es el procesador de tu computadora el que hace el trabajo pesado, no nuestros servidores. Por eso es tan rápido y 100% privado.",
        faq2_q: "¿Puedo usar Compressly en mi celular?",
        faq2_a: "Sí, nuestra interfaz está optimizada para dispositivos móviles. Puedes tomar una foto con tu cámara y comprimirla instantáneamente desde tu navegador Safari o Chrome en iOS y Android.",
        faq3_q: "¿Qué significa el Escudo Anti-Rastreo (GPS)?",
        faq3_a: "Las cámaras modernas (y los celulares) guardan datos invisibles dentro de la foto, llamados EXIF. Estos datos incluyen las coordenadas GPS exactas de dónde tomaste la foto, el tipo de cámara, y la fecha. El Escudo Anti-Rastreo (Función PRO) borra todos esos datos para que puedas subir tu imagen a internet sin revelar tu ubicación.",
        footer_rights: "© 2026 Compressly. Todos los derechos reservados.",
        footer_terms: "Términos y Condiciones",
        footer_privacy: "Política de Privacidad",
        legal_privacy_title: "Política de Privacidad",
        legal_terms_title: "Términos y Condiciones",
        legal_privacy_body: `<div class="space-y-6"><div><h3 class="text-white font-bold text-lg mb-2">1. Privacidad Local y Cero Servidores</h3><p class="leading-relaxed">En Compressly, garantizamos que tus imágenes nunca abandonan tu dispositivo. Todo el procesamiento y la compresión se realizan localmente en tu navegador web utilizando la memoria y el procesador de tu equipo.</p></div><div><h3 class="text-white font-bold text-lg mb-2">2. Recopilación de Datos</h3><p class="leading-relaxed">No recopilamos, almacenamos, copiamos ni transferimos tus imágenes, fotografías o archivos. Al no existir un servidor de subida en nuestra arquitectura, es técnicamente imposible para nosotros o para terceros acceder a tu contenido.</p></div><div><h3 class="text-white font-bold text-lg mb-2">3. Uso de Cookies Analíticas</h3><p class="leading-relaxed">Utilizamos cookies esenciales únicamente para el funcionamiento básico de la interfaz y para medir el tráfico general de la plataforma (estadísticas anónimas), sin rastrear ni almacenar información de identidad personal.</p></div></div>`,
        legal_terms_body: `<div class="space-y-6"><div><h3 class="text-white font-bold text-lg mb-2">1. Uso de la Herramienta</h3><p class="leading-relaxed">Compressly se proporciona "tal cual". Al usar nuestra plataforma, aceptas utilizarla bajo tu propia responsabilidad. Es la herramienta ideal para la optimización de catálogos e-commerce, diseño web y fotografía profesional.</p></div><div><h3 class="text-white font-bold text-lg mb-2">2. Límites de Uso General</h3><p class="leading-relaxed">El uso de la herramienta está optimizado para procesar archivos de hasta 10MB de peso por imagen en los formatos oficialmente permitidos (JPG, PNG, WEBP).</p></div><div><h3 class="text-white font-bold text-lg mb-2">3. Propiedad Intelectual y Marca</h3><p class="leading-relaxed">El código fuente, los algoritmos de interfaz, el diseño visual y la marca "Compressly" son propiedad exclusiva de Compressly. No está permitida la copia, clonación o reproducción del diseño de esta interfaz sin autorización explícita.</p></div></div>`,
        profile_greeting: "Hola, Creador",
        profile_status: "Perfil Local Activo",
        profile_impact_title: "Impacto Global",
        profile_impact_sub: "Has ahorrado al planeta:",
        profile_sync_title: "☁️ Sincronizar Nube",
        profile_sync_sub: "Crea tu cuenta gratis para guardar tu impacto y configuraciones en la nube.",
        profile_btn_google: "Continuar con Google",
        profile_divider: "O CON CORREO",
        profile_email_ph: "Tu correo electrónico",
        profile_pass_ph: "Crea una contraseña",
        profile_btn_submit: "Crear Cuenta / Entrar",
        // 🚀 NUEVOS: Muro de Pago Premium
        premium_title: "Función Exclusiva PRO",
        premium_desc: "Estás intentando usar el poder total. Únete a nuestra lista VIP y obtén acceso de por vida por solo <span class='inline-block bg-green-500/20 text-green-600 dark:text-green-400 font-black px-2.5 py-0.5 rounded-md border border-green-500/30 shadow-[0_0_10px_rgba(34,197,94,0.2)]'>$19.99</span>. ¡Hablemos por WhatsApp para activarlo ahora!",
        premium_email_ph: "Tu mejor correo electrónico",
        premium_btn: "Quiero ser PRO",
        premium_cancel: "Quizás más tarde",
        // Chatbot
        bot_title: "Asistente Virtual",
        bot_status: "En línea ahora",
        bot_welcome: "¡Hola! 👋 Soy tu asistente virtual. ¿En qué puedo ayudarte a optimizar tu flujo de trabajo hoy?",
        // 🚀 NUEVOS: Textos de Marca de Agua
        wm_pos_label: "Posición",
        wm_size_label: "Tamaño",
        wm_pos_br: "Abajo Derecha",
        wm_pos_bl: "Abajo Izquierda",
        wm_pos_tr: "Arriba Derecha",
        wm_pos_tl: "Arriba Izquierda",
        wm_pos_center: "Centro",
        wm_size_sm: "Pequeño",
        wm_size_md: "Medio",
        wm_size_lg: "Grande",
        wm_logo_selected: "Logo seleccionado ✓",
        // 🟢 NUEVOS: Textos para los Puntos de Navegación (Dots)
        dot_inicio: "Inicio",
        dot_features: "Características",
        dot_how: "Cómo funciona",
        dot_test: "Testimonios",
        dot_price: "Planes PRO",
        dot_faq: "FAQ",
        // 🚀 NUEVOS: Dashboard y Beta
        beta_badge: "Beta",
        beta_access: "Acceso Beta",
        stat_title: "Estadísticas de Uso",
        stat_processed: "Imágenes Procesadas:",
        stat_webp: "WebP (Recomendado)",
    },
    en: {
        nav_features: "Features",
        nav_how: "How it Works",
        nav_privacy: "Privacy",
        nav_impact: "Impact:",
        nav_impact_total: "Total Impact:",
        hero_title_1: "Smart compression.",
        hero_title_2: "Flawless quality.",
        hero_subtitle: "Premium optimization happening right on your device. Faster speeds, maximum privacy, and zero limits.",
        drop_main: "Drop your images here",
        drop_sub: "or click to browse your files",
        drop_limit: '<i data-lucide="shield-check" class="w-4 h-4"></i> 10MB Limit (JPG, PNG, WEBP)',
        settings_title: "Basic Settings",
        settings_quality: "Quality",
        settings_format: "Output format",
        format_original: "ORIGINAL",
        pro_title: "PRO Tools",
        pro_badge: "Premium Features",
        resize_label: "Resize",
        resize_0: "Keep Original",
        resize_4k: "4K (Max 3840px)",
        resize_fhd: "Full HD (Max 1920px)",
        resize_web: "Web / Social (Max 1080px)",
        resize_mini: "Mini / Fast (Max 720px)",
        resize_mobile: "Mobile / Email (Max 480px)",
        resize_icon: "Icon / Profile (Max 360px)",
        watermark_label: "Watermark",
        watermark_placeholder: "@YourBrand or Text...",
        anti_track_label: "Anti-Tracking",
        anti_track_sub: "Clear GPS / EXIF",
        btn_compress: "Compress Images",
        preview_original: "Original",
        preview_result: "Result",
        waiting_image: "Waiting for image",
        waiting_magic: "Waiting for magic...",
        stats_title: "Weight Savings",
        stats_waiting: "Waiting for image...",
        btn_download: "Download Image",
        tech_title_1: "Cutting-Edge",
        tech_title_2: "Technology",
        tech_subtitle: "Why Compressly is the ultimate tool for professionals.",
        tech_local_title: "Local Compression",
        tech_local_desc: "We use your device's processor. No waiting queues, no server downtime, instant speed.",
        tech_formats_title: "Multiple Formats",
        tech_formats_desc: "Full support for JPG, PNG, and automatic conversion to WebP for next-gen websites.",
        tech_privacy_title: "Military Privacy",
        tech_privacy_desc: "Your images never travel over the internet. Processed and kept in your RAM. 100% hack-free.",
        tech_privacy_link: 'Read legal policy <i data-lucide="arrow-right" class="w-3 h-3"></i>',
        magic_title_1: "How the",
        magic_title_2: "Magic Happens?",
        magic_subtitle: "An optimization flow that never leaves your screen.",
        magic_step1_title: "1. Selection",
        magic_step1_desc: "Drop your image up to 10MB. The file is read solely by your device's browser.",
        magic_step2_title: "2. Local Engine",
        magic_step2_desc: "Your computer's processor compresses the pixels using advanced tech without internet.",
        magic_step3_title: "3. Export",
        magic_step3_desc: "Get the optimized image instantly. Zero upload or download times from servers.",
        batch_title: "Image Batch",
        batch_folders: "Folders",
        batch_prefix: "Prefix (Optional)",
        batch_saving: "Batch Savings",
        batch_waiting: "Waiting for order...",
        batch_queue: "In queue",
        batch_btn_download: "Download ZIP",
        test_title_1: "Loved by",
        test_title_2: "Professionals",
        test_sub: "Thousands of gigabytes saved worldwide.",
        test1_text: '"Managing e-commerce stores is my daily life. I used to waste hours uploading photos to other compressors. With Compressly, I process entire batches in seconds without leaving my screen."',
        test1_role: "Web Designer",
        test2_text: '"As a photographer, my worst nightmare is having my original material stolen. Knowing that compression is 100% local in my RAM gives me priceless peace of mind."',
        test2_role: "Professional Photographer",
        test3_text: '"The batch renaming tool and ZIP folder organization saved me from paying an assistant. It is crazy that this works directly in the browser."',
        test3_role: "Marketing Agency",
        price_title_1: "Simple Plans,",
        price_title_2: "Absolute Power",
        price_sub: "Choose the plan that fits your workflow.",
        plan_free_title: "Essential",
        plan_free_sub: "Perfect for occasional and personal use.",
        plan_free_price: "$0",
        plan_free_time: "/ lifetime",
        plan_free_f1: "Local Compression (No internet)",
        plan_free_f2: "Up to 3 images at once",
        plan_free_f3: "Maximum 10MB per file",
        plan_free_f4: "Resize and Watermark",
        plan_free_f5: "ZIP Folders and GPS Shield",
        plan_free_btn: "Start for Free",
        plan_pro_badge: "Most Popular",
        plan_pro_sub: "For agencies, photographers, and e-commerce.",
        plan_pro_price: "$19.99",
        plan_pro_time: "/ lifetime",
        plan_pro_f1: "UNLIMITED image batches",
        plan_pro_f2: "Giant files (+10MB)",
        plan_pro_f3: "Watermark and Smart Resizing",
        plan_pro_f4: "Anti-Tracking Shield (GPS)",
        plan_pro_f5: "Automatic ZIP organization",
        plan_pro_btn: "Get PRO Access",
        faq_title: "Frequently Asked Questions",
        faq1_q: "Do my photos really not upload to the internet?",
        faq1_a: "Absolutely. Compressly uses a technology called WebAssembly. The entire compression engine is downloaded to your browser the first time you enter. When you drag a photo, your computer's processor does the heavy lifting, not our servers. That's why it's so fast and 100% private.",
        faq2_q: "Can I use Compressly on my phone?",
        faq2_a: "Yes, our interface is optimized for mobile devices. You can take a photo with your camera and compress it instantly from your Safari or Chrome browser on iOS and Android.",
        faq3_q: "What does the Anti-Tracking Shield (GPS) mean?",
        faq3_a: "Modern cameras (and phones) save invisible data inside the photo, called EXIF. This data includes the exact GPS coordinates of where you took the photo, the camera type, and the date. The Anti-Tracking Shield (PRO Feature) deletes all that data so you can upload your image to the internet without revealing your location.",
        footer_rights: "© 2026 Compressly. All rights reserved.",
        footer_terms: "Terms and Conditions",
        footer_privacy: "Privacy Policy",
        legal_privacy_title: "Privacy Policy",
        legal_terms_title: "Terms and Conditions",
        legal_privacy_body: `<div class="space-y-6"><div><h3 class="text-white font-bold text-lg mb-2">1. Local Privacy and Zero Servers</h3><p class="leading-relaxed">At Compressly, we guarantee that your images never leave your device. All processing and compression are done locally in your web browser using your device's memory and processor.</p></div><div><h3 class="text-white font-bold text-lg mb-2">2. Data Collection</h3><p class="leading-relaxed">We do not collect, store, copy, or transfer your images, photographs, or files. Since there is no upload server in our architecture, it is technically impossible for us or third parties to access your content.</p></div><div><h3 class="text-white font-bold text-lg mb-2">3. Use of Analytical Cookies</h3><p class="leading-relaxed">We use essential cookies solely for the basic functioning of the interface and to measure the general traffic of the platform (anonymous statistics), without tracking or storing personal identity information.</p></div></div>`,
        legal_terms_body: `<div class="space-y-6"><div><h3 class="text-white font-bold text-lg mb-2">1. Use of the Tool</h3><p class="leading-relaxed">Compressly is provided "as is". By using our platform, you agree to use it at your own risk. It is the ideal tool for optimizing e-commerce catalogs, web design, and professional photography.</p></div><div><h3 class="text-white font-bold text-lg mb-2">2. General Usage Limits</h3><p class="leading-relaxed">The use of the tool is optimized to process files up to 10MB in weight per image in the officially supported formats (JPG, PNG, WEBP).</p></div><div><h3 class="text-white font-bold text-lg mb-2">3. Intellectual Property and Brand</h3><p class="leading-relaxed">The source code, interface algorithms, visual design, and the "Compressly" brand are the exclusive property of Compressly. Copying, cloning, or reproducing the design of this interface without explicit authorization is not permitted.</p></div></div>`,
        profile_greeting: "Hello, Creator",
        profile_status: "Local Profile Active",
        profile_impact_title: "Global Impact",
        profile_impact_sub: "You've saved the planet:",
        profile_sync_title: "☁️ Cloud Sync",
        profile_sync_sub: "Create your free account to save your impact and settings in the cloud.",
        profile_btn_google: "Continue with Google",
        profile_divider: "OR WITH EMAIL",
        profile_email_ph: "Your email address",
        profile_pass_ph: "Create a password",
        profile_btn_submit: "Create Account / Login",
        // 🚀 NUEVOS: Muro de Pago Premium
        premium_title: "Exclusive PRO Feature",
        premium_desc: "You are trying to use the full power. Join our VIP list and get lifetime access for only <span class='inline-block bg-green-500/20 text-green-600 dark:text-green-400 font-black px-2.5 py-0.5 rounded-md border border-green-500/30 shadow-[0_0_10px_rgba(34,197,94,0.2)]'>$19.99</span>. Let's chat on WhatsApp to activate it now!",
        premium_email_ph: "Your best email address",
        premium_btn: "I want to be PRO",
        premium_cancel: "Maybe later",
        // Chatbot
        bot_title: "Virtual Assistant",
        bot_status: "Online now",
        bot_welcome: "Hello! 👋 I'm your virtual assistant. How can I help you optimize your workflow today?",
        // 🚀 NUEVOS: Textos de Marca de Agua
        wm_pos_label: "Position",
        wm_size_label: "Size",
        wm_pos_br: "Bottom Right",
        wm_pos_bl: "Bottom Left",
        wm_pos_tr: "Top Right",
        wm_pos_tl: "Top Left",
        wm_pos_center: "Center",
        wm_size_sm: "Small",
        wm_size_md: "Medium",
        wm_size_lg: "Large",
        wm_logo_selected: "Logo selected ✓",
        // 🟢 NUEVOS: Textos para los Puntos de Navegación (Dots)
        dot_inicio: "Home",
        dot_features: "Features",
        dot_how: "How it Works",
        dot_test: "Testimonials",
        dot_price: "PRO Plans",
        dot_faq: "FAQ",
        // 🚀 NUEVOS: Dashboard y Beta
        beta_badge: "Beta",
        beta_access: "Beta Access",
        stat_title: "Usage Statistics",
        stat_processed: "Processed Images:",
        stat_webp: "WebP (Recommended)",
    }
};

let currentLanguage = localStorage.getItem('compressly_lang') || 'es';

function applyLanguage(lang) {
    document.querySelectorAll('[data-i18n]').forEach(element => {
        const key = element.getAttribute('data-i18n');

        // 🚀 NUEVO: Si hay un logo subido en memoria, reemplazamos el placeholder normal por el de "Logo seleccionado"
        if (key === 'watermark_placeholder' && typeof customLogoImage !== 'undefined' && customLogoImage !== null) {
            if (translations[lang] && translations[lang].wm_logo_selected) {
                element.placeholder = translations[lang].wm_logo_selected;
            }
            return; // Salimos de esta vuelta para no sobreescribir con la frase vieja
        }

        if (translations[lang] && translations[lang][key]) {
            if (element.tagName === 'INPUT') {
                element.placeholder = translations[lang][key];
            } else if (element.classList.contains('scroll-dot')) {
                // 🚀 TRUCO: Traduce el tooltip de los puntos
                element.setAttribute('data-tooltip', translations[lang][key]);
            } else {
                element.innerHTML = translations[lang][key];
            }
        }
    });

    if (currentLangLabel) currentLangLabel.innerText = lang.toUpperCase();
    if (currentLangLabelMobile) currentLangLabelMobile.innerText = lang.toUpperCase();

    localStorage.setItem('compressly_lang', lang);
    lucide.createIcons();
}

function toggleLanguage() {
    if (navigator.vibrate) navigator.vibrate(20);
    currentLanguage = currentLanguage === 'es' ? 'en' : 'es';
    applyLanguage(currentLanguage);

    // Necesitamos invocar a Notify que está en otro script, así que verificamos que exista
    if (typeof Notify !== 'undefined') {
        Notify.show('Idioma actualizado', currentLanguage === 'es' ? 'Se ha cambiado al Español' : 'Language changed to English', 'info');
    }
}

if (langToggle) langToggle.addEventListener('click', toggleLanguage);
if (langToggleMobile) langToggleMobile.addEventListener('click', toggleLanguage);

applyLanguage(currentLanguage);